Ashwin
teampowstik/Powstik-Back pull request #69
Opened 2022-07-17 13:11 UTC by ash-02

created routes for reviews and coupons

2022-07-17 16:02 UTC, akhilsrinivasp commented on Files/coupons/utils.py
> +from unittest import result
unnecessary imports can be removed ig

2022-07-19 17:36 UTC, AviralJ58 requested changes
Check out for comments. Also common.db is conflicting. Try deleting it and push. If it doesn't work then temporarily add the db from the main branch and push with that to solve the conflict.

2022-07-19 17:36 UTC, AviralJ58 commented on Files/coupons/utils.py
> +    coupon_code = generate_coupon_code()
Coupon code must also be taken as input. For example there can be a coupon "POW100" offering flat Rs. 100 discount. Or something related to bank offers and stuff. Code shouldn't be random.

2022-07-19 17:36 UTC, AviralJ58 commented on Files/models.py
>      review = db.Column(db.String(80), nullable=False)
nullable=True as some users can just rate and not leave a review.

2022-07-19 17:36 UTC, AviralJ58 commented on Files/models.py
>      rating = db.Column(db.Integer, nullable=False)
Data type float to allow rating like 4.5

2024-11-13 20:47 UTC, closed without merging